app:
  name: extension-spr

server:
  port: 9001

spring:
  datasource:
    url: jdbc:postgresql://ups-fo-spr.mobifone.vn:5432/spr
    username: spr
    password: Dts@12345
    driverClassName: org.postgresql.Driver



