server:
  port: 9001

spring:
  datasource:
    # Primary database
    primary:
      jdbc-url: jdbc:postgresql://ups-fo-spr-database.mobifone.vn:5432/spr
      username: spr
      password: Dts@12345
      driverClassName: org.postgresql.Driver

    # Secondary database
    secondary:
      jdbc-url: jdbc:oracle:thin:@10.3.17.153:1521:db01
      username: VASP4_SUBS
      password: abcd1234
      driverClassName: oracle.jdbc.OracleDriver

file:
  upload-dir: D:/DTS/Uploads