app:
  name: spr-config
  config-path: D:/Source/DTS/scan-register-tool/config-file
  scan-folder: /spr/register1-%d-%d-%d/
  auto-import: /home/spr/import/

server:
  port: 9001

spring:
  profiles:
    active: local-prod
  jpa:
    show-sql: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

security:
  authentication:
    jwt:
      secret-key: spr-config
      token-validity-in-seconds: 360000000
      token-validity-in-seconds-for-remember-me: 720000000

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "Authorization,Link,X-Total-Count"
  allow-credentials: true
  max-age: 1800

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
