app:
  name: extension-spr
spring:
    datasource:
        url: jdbc:postgresql://10.10.88.182:5432/spr
        username: postgres
        password: 123456
        driverClassName: org.postgresql.Driver
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
    profiles:
        active: local
    
        
security:
    authentication:
        jwt:
            secret-key: beeland
            token-validity-in-seconds: 360000000
            token-validity-in-seconds-for-remember-me: 720000000
cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
    exposed-headers: "Authorization,Link,X-Total-Count"
    allow-credentials: true
    max-age: 1800
server:
    port : 8080

