server:
  port: 9001

spring:
  datasource:
    # Database SPR
    primary:
      jdbc-url: jdbc:postgresql://ups-fo-spr-database.mobifone.vn:5432/spr
      username: spr
      password: spr
      driverClassName: org.postgresql.Driver

    # Database VASP
    secondary:
      jdbc-url: jdbc:oracle:thin:@10.50.9.161:1521:vasp1
      username: flowone_spr
      password: fl0wOne$Mbf2021
      driverClassName: oracle.jdbc.OracleDriver

    # Database ILINK
    third:
      jdbc-url: jdbc:postgresql://ups-fo-spr-database.mobifone.vn:5432/ilink
      username: ilink
      password: ilink
      driverClassName: org.postgresql.Driver

    # Database ILARC
    fourth:
      jdbc-url: jdbc:postgresql://10.3.17.139:5432/ilarc
      username: admin_report
      password: admin_report
      driverClassName: org.postgresql.Driver

app:
  config-path: /web-admin/config/
  auto-import: /home/spr/import/

file:
  upload-dir: /home/upload




