app:
  name: extension-spr
spring:
    datasource:
        url: jdbc:postgresql://10.3.17.141:5432/spr
        username: spr
        password: Dts@12345
        driverClassName: org.postgresql.Driver
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true

security:
    authentication:
        jwt:
            secret-key: spr-config
            token-validity-in-seconds: 360000000
            token-validity-in-seconds-for-remember-me: 720000000

cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
    exposed-headers: "Authorization,Link,X-Total-Count"
    allow-credentials: true
    max-age: 1800
server:
    port : 9001

